# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  image: 'knote-js'
  namespace: 'learnkube8s'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'kdipa'
    steps: 

    - task: oc-cmd@3
      displayName: openshif console login 
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'NonProd-Openshift'
        cmd: 'version'
        uselocalOc: true
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        containerRegistry: 'docker-login'
        repository: '$(namespace)/$(image)'
        dockerfile: '$(Build.SourcesDirectory)/knote-js/application/Dockerfile'
        tags: '$(Build.BuildId)-amd64'     
    - task: Docker@2
      displayName: push image to ACR
      inputs:
         containerRegistry: 'docker-login'
         repository: '$(namespace)/$(image)'
         command: push
         tags: '$(Build.BuildId)-amd64'    
    - task: CmdLine@2
      displayName: deployment of application  
      inputs:
        script: 'kubectl set image deployment/knote knote=stgacr.azurecr.io/learnkube8s/knote-js:$(Build.BuildId)-amd64 -n learnkube8s'
        workingDirectory: '$(Build.SourcesDirectory)/knote-js/application/kube/'
        